version: '3'

services:
  php:
    build:
      context: docker/php
      args:
        #- WITH_XDEBUG=true
        #- APP_ENV=dev
        - XDEBUG_REMOTE_HOST=10.233.1.83
    container_name: git-actions-php
    env_file: docker/.env
    volumes:
      - .:/var/www/html:rw
    tty: true